//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace SimpleCRUDApp.Web
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class DIGAWEBEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new DIGAWEBEntities object using the connection string found in the 'DIGAWEBEntities' section of the application configuration file.
        /// </summary>
        public DIGAWEBEntities() : base("name=DIGAWEBEntities", "DIGAWEBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DIGAWEBEntities object.
        /// </summary>
        public DIGAWEBEntities(string connectionString) : base(connectionString, "DIGAWEBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new DIGAWEBEntities object.
        /// </summary>
        public DIGAWEBEntities(EntityConnection connection) : base(connection, "DIGAWEBEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<VLMFFMP> VLMFFMP
        {
            get
            {
                if ((_VLMFFMP == null))
                {
                    _VLMFFMP = base.CreateObjectSet<VLMFFMP>("VLMFFMP");
                }
                return _VLMFFMP;
            }
        }
        private ObjectSet<VLMFFMP> _VLMFFMP;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<VLMFIAL> VLMFIAL
        {
            get
            {
                if ((_VLMFIAL == null))
                {
                    _VLMFIAL = base.CreateObjectSet<VLMFIAL>("VLMFIAL");
                }
                return _VLMFIAL;
            }
        }
        private ObjectSet<VLMFIAL> _VLMFIAL;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the VLMFFMP EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVLMFFMP(VLMFFMP vLMFFMP)
        {
            base.AddObject("VLMFFMP", vLMFFMP);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the VLMFIAL EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVLMFIAL(VLMFIAL vLMFIAL)
        {
            base.AddObject("VLMFIAL", vLMFIAL);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="VLMFFMP")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VLMFFMP : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new VLMFFMP object.
        /// </summary>
        /// <param name="fMPNHIS">Initial value of the FMPNHIS property.</param>
        /// <param name="fMPSEXO">Initial value of the FMPSEXO property.</param>
        /// <param name="fMPAPE1">Initial value of the FMPAPE1 property.</param>
        public static VLMFFMP CreateVLMFFMP(global::System.Int32 fMPNHIS, global::System.String fMPSEXO, global::System.String fMPAPE1)
        {
            VLMFFMP vLMFFMP = new VLMFFMP();
            vLMFFMP.FMPNHIS = fMPNHIS;
            vLMFFMP.FMPSEXO = fMPSEXO;
            vLMFFMP.FMPAPE1 = fMPAPE1;
            return vLMFFMP;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FMPCOPO
        {
            get
            {
                return _FMPCOPO;
            }
            set
            {
                OnFMPCOPOChanging(value);
                ReportPropertyChanging("FMPCOPO");
                _FMPCOPO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FMPCOPO");
                OnFMPCOPOChanged();
            }
        }
        private global::System.String _FMPCOPO;
        partial void OnFMPCOPOChanging(global::System.String value);
        partial void OnFMPCOPOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FMPDIRE
        {
            get
            {
                return _FMPDIRE;
            }
            set
            {
                OnFMPDIREChanging(value);
                ReportPropertyChanging("FMPDIRE");
                _FMPDIRE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FMPDIRE");
                OnFMPDIREChanged();
            }
        }
        private global::System.String _FMPDIRE;
        partial void OnFMPDIREChanging(global::System.String value);
        partial void OnFMPDIREChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FMPEXIT
        {
            get
            {
                return _FMPEXIT;
            }
            set
            {
                OnFMPEXITChanging(value);
                ReportPropertyChanging("FMPEXIT");
                _FMPEXIT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FMPEXIT");
                OnFMPEXITChanged();
            }
        }
        private global::System.String _FMPEXIT;
        partial void OnFMPEXITChanging(global::System.String value);
        partial void OnFMPEXITChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FMPLOCA
        {
            get
            {
                return _FMPLOCA;
            }
            set
            {
                OnFMPLOCAChanging(value);
                ReportPropertyChanging("FMPLOCA");
                _FMPLOCA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FMPLOCA");
                OnFMPLOCAChanged();
            }
        }
        private global::System.String _FMPLOCA;
        partial void OnFMPLOCAChanging(global::System.String value);
        partial void OnFMPLOCAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FMPLOHC
        {
            get
            {
                return _FMPLOHC;
            }
            set
            {
                OnFMPLOHCChanging(value);
                ReportPropertyChanging("FMPLOHC");
                _FMPLOHC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FMPLOHC");
                OnFMPLOHCChanged();
            }
        }
        private global::System.String _FMPLOHC;
        partial void OnFMPLOHCChanging(global::System.String value);
        partial void OnFMPLOHCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> FMPNACI
        {
            get
            {
                return _FMPNACI;
            }
            set
            {
                OnFMPNACIChanging(value);
                ReportPropertyChanging("FMPNACI");
                _FMPNACI = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FMPNACI");
                OnFMPNACIChanged();
            }
        }
        private Nullable<global::System.DateTime> _FMPNACI;
        partial void OnFMPNACIChanging(Nullable<global::System.DateTime> value);
        partial void OnFMPNACIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FMPNCSS
        {
            get
            {
                return _FMPNCSS;
            }
            set
            {
                OnFMPNCSSChanging(value);
                ReportPropertyChanging("FMPNCSS");
                _FMPNCSS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FMPNCSS");
                OnFMPNCSSChanged();
            }
        }
        private global::System.String _FMPNCSS;
        partial void OnFMPNCSSChanging(global::System.String value);
        partial void OnFMPNCSSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FMPNDNI
        {
            get
            {
                return _FMPNDNI;
            }
            set
            {
                OnFMPNDNIChanging(value);
                ReportPropertyChanging("FMPNDNI");
                _FMPNDNI = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FMPNDNI");
                OnFMPNDNIChanged();
            }
        }
        private global::System.String _FMPNDNI;
        partial void OnFMPNDNIChanging(global::System.String value);
        partial void OnFMPNDNIChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 FMPNHIS
        {
            get
            {
                return _FMPNHIS;
            }
            set
            {
                if (_FMPNHIS != value)
                {
                    OnFMPNHISChanging(value);
                    ReportPropertyChanging("FMPNHIS");
                    _FMPNHIS = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FMPNHIS");
                    OnFMPNHISChanged();
                }
            }
        }
        private global::System.Int32 _FMPNHIS;
        partial void OnFMPNHISChanging(global::System.Int32 value);
        partial void OnFMPNHISChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FMPNHAG
        {
            get
            {
                return _FMPNHAG;
            }
            set
            {
                OnFMPNHAGChanging(value);
                ReportPropertyChanging("FMPNHAG");
                _FMPNHAG = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FMPNHAG");
                OnFMPNHAGChanged();
            }
        }
        private Nullable<global::System.Int32> _FMPNHAG;
        partial void OnFMPNHAGChanging(Nullable<global::System.Int32> value);
        partial void OnFMPNHAGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FMPNHDH
        {
            get
            {
                return _FMPNHDH;
            }
            set
            {
                OnFMPNHDHChanging(value);
                ReportPropertyChanging("FMPNHDH");
                _FMPNHDH = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FMPNHDH");
                OnFMPNHDHChanged();
            }
        }
        private Nullable<global::System.Int32> _FMPNHDH;
        partial void OnFMPNHDHChanging(Nullable<global::System.Int32> value);
        partial void OnFMPNHDHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> FMPNHMF
        {
            get
            {
                return _FMPNHMF;
            }
            set
            {
                OnFMPNHMFChanging(value);
                ReportPropertyChanging("FMPNHMF");
                _FMPNHMF = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("FMPNHMF");
                OnFMPNHMFChanged();
            }
        }
        private Nullable<global::System.Int32> _FMPNHMF;
        partial void OnFMPNHMFChanging(Nullable<global::System.Int32> value);
        partial void OnFMPNHMFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FMPNOMB
        {
            get
            {
                return _FMPNOMB;
            }
            set
            {
                OnFMPNOMBChanging(value);
                ReportPropertyChanging("FMPNOMB");
                _FMPNOMB = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FMPNOMB");
                OnFMPNOMBChanged();
            }
        }
        private global::System.String _FMPNOMB;
        partial void OnFMPNOMBChanging(global::System.String value);
        partial void OnFMPNOMBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FMPORIG
        {
            get
            {
                return _FMPORIG;
            }
            set
            {
                OnFMPORIGChanging(value);
                ReportPropertyChanging("FMPORIG");
                _FMPORIG = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FMPORIG");
                OnFMPORIGChanged();
            }
        }
        private global::System.String _FMPORIG;
        partial void OnFMPORIGChanging(global::System.String value);
        partial void OnFMPORIGChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FMPPROV
        {
            get
            {
                return _FMPPROV;
            }
            set
            {
                OnFMPPROVChanging(value);
                ReportPropertyChanging("FMPPROV");
                _FMPPROV = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FMPPROV");
                OnFMPPROVChanged();
            }
        }
        private global::System.String _FMPPROV;
        partial void OnFMPPROVChanging(global::System.String value);
        partial void OnFMPPROVChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FMPSEXO
        {
            get
            {
                return _FMPSEXO;
            }
            set
            {
                OnFMPSEXOChanging(value);
                ReportPropertyChanging("FMPSEXO");
                _FMPSEXO = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FMPSEXO");
                OnFMPSEXOChanged();
            }
        }
        private global::System.String _FMPSEXO;
        partial void OnFMPSEXOChanging(global::System.String value);
        partial void OnFMPSEXOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FMPTASS
        {
            get
            {
                return _FMPTASS;
            }
            set
            {
                OnFMPTASSChanging(value);
                ReportPropertyChanging("FMPTASS");
                _FMPTASS = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FMPTASS");
                OnFMPTASSChanged();
            }
        }
        private global::System.String _FMPTASS;
        partial void OnFMPTASSChanging(global::System.String value);
        partial void OnFMPTASSChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FMPTFN2
        {
            get
            {
                return _FMPTFN2;
            }
            set
            {
                OnFMPTFN2Changing(value);
                ReportPropertyChanging("FMPTFN2");
                _FMPTFN2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FMPTFN2");
                OnFMPTFN2Changed();
            }
        }
        private global::System.String _FMPTFN2;
        partial void OnFMPTFN2Changing(global::System.String value);
        partial void OnFMPTFN2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FMPTFNO
        {
            get
            {
                return _FMPTFNO;
            }
            set
            {
                OnFMPTFNOChanging(value);
                ReportPropertyChanging("FMPTFNO");
                _FMPTFNO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FMPTFNO");
                OnFMPTFNOChanged();
            }
        }
        private global::System.String _FMPTFNO;
        partial void OnFMPTFNOChanging(global::System.String value);
        partial void OnFMPTFNOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FMPUBIC
        {
            get
            {
                return _FMPUBIC;
            }
            set
            {
                OnFMPUBICChanging(value);
                ReportPropertyChanging("FMPUBIC");
                _FMPUBIC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FMPUBIC");
                OnFMPUBICChanged();
            }
        }
        private global::System.String _FMPUBIC;
        partial void OnFMPUBICChanging(global::System.String value);
        partial void OnFMPUBICChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String FMPAPE1
        {
            get
            {
                return _FMPAPE1;
            }
            set
            {
                OnFMPAPE1Changing(value);
                ReportPropertyChanging("FMPAPE1");
                _FMPAPE1 = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("FMPAPE1");
                OnFMPAPE1Changed();
            }
        }
        private global::System.String _FMPAPE1;
        partial void OnFMPAPE1Changing(global::System.String value);
        partial void OnFMPAPE1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FMPAPE2
        {
            get
            {
                return _FMPAPE2;
            }
            set
            {
                OnFMPAPE2Changing(value);
                ReportPropertyChanging("FMPAPE2");
                _FMPAPE2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FMPAPE2");
                OnFMPAPE2Changed();
            }
        }
        private global::System.String _FMPAPE2;
        partial void OnFMPAPE2Changing(global::System.String value);
        partial void OnFMPAPE2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FMPACLA
        {
            get
            {
                return _FMPACLA;
            }
            set
            {
                OnFMPACLAChanging(value);
                ReportPropertyChanging("FMPACLA");
                _FMPACLA = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FMPACLA");
                OnFMPACLAChanged();
            }
        }
        private global::System.String _FMPACLA;
        partial void OnFMPACLAChanging(global::System.String value);
        partial void OnFMPACLAChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FMPALER
        {
            get
            {
                return _FMPALER;
            }
            set
            {
                OnFMPALERChanging(value);
                ReportPropertyChanging("FMPALER");
                _FMPALER = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FMPALER");
                OnFMPALERChanged();
            }
        }
        private global::System.String _FMPALER;
        partial void OnFMPALERChanging(global::System.String value);
        partial void OnFMPALERChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FMPBORN
        {
            get
            {
                return _FMPBORN;
            }
            set
            {
                OnFMPBORNChanging(value);
                ReportPropertyChanging("FMPBORN");
                _FMPBORN = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FMPBORN");
                OnFMPBORNChanged();
            }
        }
        private global::System.String _FMPBORN;
        partial void OnFMPBORNChanging(global::System.String value);
        partial void OnFMPBORNChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FMPPARE
        {
            get
            {
                return _FMPPARE;
            }
            set
            {
                OnFMPPAREChanging(value);
                ReportPropertyChanging("FMPPARE");
                _FMPPARE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FMPPARE");
                OnFMPPAREChanged();
            }
        }
        private global::System.String _FMPPARE;
        partial void OnFMPPAREChanging(global::System.String value);
        partial void OnFMPPAREChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FMPRESI
        {
            get
            {
                return _FMPRESI;
            }
            set
            {
                OnFMPRESIChanging(value);
                ReportPropertyChanging("FMPRESI");
                _FMPRESI = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FMPRESI");
                OnFMPRESIChanged();
            }
        }
        private global::System.String _FMPRESI;
        partial void OnFMPRESIChanging(global::System.String value);
        partial void OnFMPRESIChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="VLMFIAL")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VLMFIAL : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new VLMFIAL object.
        /// </summary>
        /// <param name="iALNHIS">Initial value of the IALNHIS property.</param>
        /// <param name="iALNREF">Initial value of the IALNREF property.</param>
        /// <param name="iALP__7">Initial value of the IALP__7 property.</param>
        public static VLMFIAL CreateVLMFIAL(global::System.Int32 iALNHIS, global::System.String iALNREF, global::System.String iALP__7)
        {
            VLMFIAL vLMFIAL = new VLMFIAL();
            vLMFIAL.IALNHIS = iALNHIS;
            vLMFIAL.IALNREF = iALNREF;
            vLMFIAL.IALP__7 = iALP__7;
            return vLMFIAL;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALCALT
        {
            get
            {
                return _IALCALT;
            }
            set
            {
                OnIALCALTChanging(value);
                ReportPropertyChanging("IALCALT");
                _IALCALT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALCALT");
                OnIALCALTChanged();
            }
        }
        private global::System.String _IALCALT;
        partial void OnIALCALTChanging(global::System.String value);
        partial void OnIALCALTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALCP11
        {
            get
            {
                return _IALCP11;
            }
            set
            {
                OnIALCP11Changing(value);
                ReportPropertyChanging("IALCP11");
                _IALCP11 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALCP11");
                OnIALCP11Changed();
            }
        }
        private global::System.String _IALCP11;
        partial void OnIALCP11Changing(global::System.String value);
        partial void OnIALCP11Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALCP12
        {
            get
            {
                return _IALCP12;
            }
            set
            {
                OnIALCP12Changing(value);
                ReportPropertyChanging("IALCP12");
                _IALCP12 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALCP12");
                OnIALCP12Changed();
            }
        }
        private global::System.String _IALCP12;
        partial void OnIALCP12Changing(global::System.String value);
        partial void OnIALCP12Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALCP13
        {
            get
            {
                return _IALCP13;
            }
            set
            {
                OnIALCP13Changing(value);
                ReportPropertyChanging("IALCP13");
                _IALCP13 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALCP13");
                OnIALCP13Changed();
            }
        }
        private global::System.String _IALCP13;
        partial void OnIALCP13Changing(global::System.String value);
        partial void OnIALCP13Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALCP21
        {
            get
            {
                return _IALCP21;
            }
            set
            {
                OnIALCP21Changing(value);
                ReportPropertyChanging("IALCP21");
                _IALCP21 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALCP21");
                OnIALCP21Changed();
            }
        }
        private global::System.String _IALCP21;
        partial void OnIALCP21Changing(global::System.String value);
        partial void OnIALCP21Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALCP22
        {
            get
            {
                return _IALCP22;
            }
            set
            {
                OnIALCP22Changing(value);
                ReportPropertyChanging("IALCP22");
                _IALCP22 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALCP22");
                OnIALCP22Changed();
            }
        }
        private global::System.String _IALCP22;
        partial void OnIALCP22Changing(global::System.String value);
        partial void OnIALCP22Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALCP23
        {
            get
            {
                return _IALCP23;
            }
            set
            {
                OnIALCP23Changing(value);
                ReportPropertyChanging("IALCP23");
                _IALCP23 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALCP23");
                OnIALCP23Changed();
            }
        }
        private global::System.String _IALCP23;
        partial void OnIALCP23Changing(global::System.String value);
        partial void OnIALCP23Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALCP31
        {
            get
            {
                return _IALCP31;
            }
            set
            {
                OnIALCP31Changing(value);
                ReportPropertyChanging("IALCP31");
                _IALCP31 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALCP31");
                OnIALCP31Changed();
            }
        }
        private global::System.String _IALCP31;
        partial void OnIALCP31Changing(global::System.String value);
        partial void OnIALCP31Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALCP32
        {
            get
            {
                return _IALCP32;
            }
            set
            {
                OnIALCP32Changing(value);
                ReportPropertyChanging("IALCP32");
                _IALCP32 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALCP32");
                OnIALCP32Changed();
            }
        }
        private global::System.String _IALCP32;
        partial void OnIALCP32Changing(global::System.String value);
        partial void OnIALCP32Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALCP33
        {
            get
            {
                return _IALCP33;
            }
            set
            {
                OnIALCP33Changing(value);
                ReportPropertyChanging("IALCP33");
                _IALCP33 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALCP33");
                OnIALCP33Changed();
            }
        }
        private global::System.String _IALCP33;
        partial void OnIALCP33Changing(global::System.String value);
        partial void OnIALCP33Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALDALT
        {
            get
            {
                return _IALDALT;
            }
            set
            {
                OnIALDALTChanging(value);
                ReportPropertyChanging("IALDALT");
                _IALDALT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALDALT");
                OnIALDALTChanged();
            }
        }
        private global::System.String _IALDALT;
        partial void OnIALDALTChanging(global::System.String value);
        partial void OnIALDALTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> IALDATE
        {
            get
            {
                return _IALDATE;
            }
            set
            {
                OnIALDATEChanging(value);
                ReportPropertyChanging("IALDATE");
                _IALDATE = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IALDATE");
                OnIALDATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _IALDATE;
        partial void OnIALDATEChanging(Nullable<global::System.DateTime> value);
        partial void OnIALDATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALDRAL
        {
            get
            {
                return _IALDRAL;
            }
            set
            {
                OnIALDRALChanging(value);
                ReportPropertyChanging("IALDRAL");
                _IALDRAL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALDRAL");
                OnIALDRALChanged();
            }
        }
        private global::System.String _IALDRAL;
        partial void OnIALDRALChanging(global::System.String value);
        partial void OnIALDRALChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALD__1
        {
            get
            {
                return _IALD__1;
            }
            set
            {
                OnIALD__1Changing(value);
                ReportPropertyChanging("IALD__1");
                _IALD__1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALD__1");
                OnIALD__1Changed();
            }
        }
        private global::System.String _IALD__1;
        partial void OnIALD__1Changing(global::System.String value);
        partial void OnIALD__1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALD__2
        {
            get
            {
                return _IALD__2;
            }
            set
            {
                OnIALD__2Changing(value);
                ReportPropertyChanging("IALD__2");
                _IALD__2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALD__2");
                OnIALD__2Changed();
            }
        }
        private global::System.String _IALD__2;
        partial void OnIALD__2Changing(global::System.String value);
        partial void OnIALD__2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALD__3
        {
            get
            {
                return _IALD__3;
            }
            set
            {
                OnIALD__3Changing(value);
                ReportPropertyChanging("IALD__3");
                _IALD__3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALD__3");
                OnIALD__3Changed();
            }
        }
        private global::System.String _IALD__3;
        partial void OnIALD__3Changing(global::System.String value);
        partial void OnIALD__3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALD__4
        {
            get
            {
                return _IALD__4;
            }
            set
            {
                OnIALD__4Changing(value);
                ReportPropertyChanging("IALD__4");
                _IALD__4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALD__4");
                OnIALD__4Changed();
            }
        }
        private global::System.String _IALD__4;
        partial void OnIALD__4Changing(global::System.String value);
        partial void OnIALD__4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALD__5
        {
            get
            {
                return _IALD__5;
            }
            set
            {
                OnIALD__5Changing(value);
                ReportPropertyChanging("IALD__5");
                _IALD__5 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALD__5");
                OnIALD__5Changed();
            }
        }
        private global::System.String _IALD__5;
        partial void OnIALD__5Changing(global::System.String value);
        partial void OnIALD__5Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALD__6
        {
            get
            {
                return _IALD__6;
            }
            set
            {
                OnIALD__6Changing(value);
                ReportPropertyChanging("IALD__6");
                _IALD__6 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALD__6");
                OnIALD__6Changed();
            }
        }
        private global::System.String _IALD__6;
        partial void OnIALD__6Changing(global::System.String value);
        partial void OnIALD__6Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALD__7
        {
            get
            {
                return _IALD__7;
            }
            set
            {
                OnIALD__7Changing(value);
                ReportPropertyChanging("IALD__7");
                _IALD__7 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALD__7");
                OnIALD__7Changed();
            }
        }
        private global::System.String _IALD__7;
        partial void OnIALD__7Changing(global::System.String value);
        partial void OnIALD__7Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALD__E
        {
            get
            {
                return _IALD__E;
            }
            set
            {
                OnIALD__EChanging(value);
                ReportPropertyChanging("IALD__E");
                _IALD__E = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALD__E");
                OnIALD__EChanged();
            }
        }
        private global::System.String _IALD__E;
        partial void OnIALD__EChanging(global::System.String value);
        partial void OnIALD__EChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> IALFADM
        {
            get
            {
                return _IALFADM;
            }
            set
            {
                OnIALFADMChanging(value);
                ReportPropertyChanging("IALFADM");
                _IALFADM = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IALFADM");
                OnIALFADMChanged();
            }
        }
        private Nullable<global::System.DateTime> _IALFADM;
        partial void OnIALFADMChanging(Nullable<global::System.DateTime> value);
        partial void OnIALFADMChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> IALFALT
        {
            get
            {
                return _IALFALT;
            }
            set
            {
                OnIALFALTChanging(value);
                ReportPropertyChanging("IALFALT");
                _IALFALT = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IALFALT");
                OnIALFALTChanged();
            }
        }
        private Nullable<global::System.DateTime> _IALFALT;
        partial void OnIALFALTChanging(Nullable<global::System.DateTime> value);
        partial void OnIALFALTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> IALFPQ1
        {
            get
            {
                return _IALFPQ1;
            }
            set
            {
                OnIALFPQ1Changing(value);
                ReportPropertyChanging("IALFPQ1");
                _IALFPQ1 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IALFPQ1");
                OnIALFPQ1Changed();
            }
        }
        private Nullable<global::System.DateTime> _IALFPQ1;
        partial void OnIALFPQ1Changing(Nullable<global::System.DateTime> value);
        partial void OnIALFPQ1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> IALFPQ2
        {
            get
            {
                return _IALFPQ2;
            }
            set
            {
                OnIALFPQ2Changing(value);
                ReportPropertyChanging("IALFPQ2");
                _IALFPQ2 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IALFPQ2");
                OnIALFPQ2Changed();
            }
        }
        private Nullable<global::System.DateTime> _IALFPQ2;
        partial void OnIALFPQ2Changing(Nullable<global::System.DateTime> value);
        partial void OnIALFPQ2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> IALFPQ3
        {
            get
            {
                return _IALFPQ3;
            }
            set
            {
                OnIALFPQ3Changing(value);
                ReportPropertyChanging("IALFPQ3");
                _IALFPQ3 = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("IALFPQ3");
                OnIALFPQ3Changed();
            }
        }
        private Nullable<global::System.DateTime> _IALFPQ3;
        partial void OnIALFPQ3Changing(Nullable<global::System.DateTime> value);
        partial void OnIALFPQ3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALI__1
        {
            get
            {
                return _IALI__1;
            }
            set
            {
                OnIALI__1Changing(value);
                ReportPropertyChanging("IALI__1");
                _IALI__1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALI__1");
                OnIALI__1Changed();
            }
        }
        private global::System.String _IALI__1;
        partial void OnIALI__1Changing(global::System.String value);
        partial void OnIALI__1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALI__2
        {
            get
            {
                return _IALI__2;
            }
            set
            {
                OnIALI__2Changing(value);
                ReportPropertyChanging("IALI__2");
                _IALI__2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALI__2");
                OnIALI__2Changed();
            }
        }
        private global::System.String _IALI__2;
        partial void OnIALI__2Changing(global::System.String value);
        partial void OnIALI__2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALI__3
        {
            get
            {
                return _IALI__3;
            }
            set
            {
                OnIALI__3Changing(value);
                ReportPropertyChanging("IALI__3");
                _IALI__3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALI__3");
                OnIALI__3Changed();
            }
        }
        private global::System.String _IALI__3;
        partial void OnIALI__3Changing(global::System.String value);
        partial void OnIALI__3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 IALNHIS
        {
            get
            {
                return _IALNHIS;
            }
            set
            {
                if (_IALNHIS != value)
                {
                    OnIALNHISChanging(value);
                    ReportPropertyChanging("IALNHIS");
                    _IALNHIS = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("IALNHIS");
                    OnIALNHISChanged();
                }
            }
        }
        private global::System.Int32 _IALNHIS;
        partial void OnIALNHISChanging(global::System.Int32 value);
        partial void OnIALNHISChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALNOMB
        {
            get
            {
                return _IALNOMB;
            }
            set
            {
                OnIALNOMBChanging(value);
                ReportPropertyChanging("IALNOMB");
                _IALNOMB = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALNOMB");
                OnIALNOMBChanged();
            }
        }
        private global::System.String _IALNOMB;
        partial void OnIALNOMBChanging(global::System.String value);
        partial void OnIALNOMBChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IALNREF
        {
            get
            {
                return _IALNREF;
            }
            set
            {
                if (_IALNREF != value)
                {
                    OnIALNREFChanging(value);
                    ReportPropertyChanging("IALNREF");
                    _IALNREF = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("IALNREF");
                    OnIALNREFChanged();
                }
            }
        }
        private global::System.String _IALNREF;
        partial void OnIALNREFChanging(global::System.String value);
        partial void OnIALNREFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALOMS1
        {
            get
            {
                return _IALOMS1;
            }
            set
            {
                OnIALOMS1Changing(value);
                ReportPropertyChanging("IALOMS1");
                _IALOMS1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALOMS1");
                OnIALOMS1Changed();
            }
        }
        private global::System.String _IALOMS1;
        partial void OnIALOMS1Changing(global::System.String value);
        partial void OnIALOMS1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALOMS2
        {
            get
            {
                return _IALOMS2;
            }
            set
            {
                OnIALOMS2Changing(value);
                ReportPropertyChanging("IALOMS2");
                _IALOMS2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALOMS2");
                OnIALOMS2Changed();
            }
        }
        private global::System.String _IALOMS2;
        partial void OnIALOMS2Changing(global::System.String value);
        partial void OnIALOMS2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALOMS3
        {
            get
            {
                return _IALOMS3;
            }
            set
            {
                OnIALOMS3Changing(value);
                ReportPropertyChanging("IALOMS3");
                _IALOMS3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALOMS3");
                OnIALOMS3Changed();
            }
        }
        private global::System.String _IALOMS3;
        partial void OnIALOMS3Changing(global::System.String value);
        partial void OnIALOMS3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALOMS4
        {
            get
            {
                return _IALOMS4;
            }
            set
            {
                OnIALOMS4Changing(value);
                ReportPropertyChanging("IALOMS4");
                _IALOMS4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALOMS4");
                OnIALOMS4Changed();
            }
        }
        private global::System.String _IALOMS4;
        partial void OnIALOMS4Changing(global::System.String value);
        partial void OnIALOMS4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALOMS5
        {
            get
            {
                return _IALOMS5;
            }
            set
            {
                OnIALOMS5Changing(value);
                ReportPropertyChanging("IALOMS5");
                _IALOMS5 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALOMS5");
                OnIALOMS5Changed();
            }
        }
        private global::System.String _IALOMS5;
        partial void OnIALOMS5Changing(global::System.String value);
        partial void OnIALOMS5Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALOMS6
        {
            get
            {
                return _IALOMS6;
            }
            set
            {
                OnIALOMS6Changing(value);
                ReportPropertyChanging("IALOMS6");
                _IALOMS6 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALOMS6");
                OnIALOMS6Changed();
            }
        }
        private global::System.String _IALOMS6;
        partial void OnIALOMS6Changing(global::System.String value);
        partial void OnIALOMS6Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALOMS7
        {
            get
            {
                return _IALOMS7;
            }
            set
            {
                OnIALOMS7Changing(value);
                ReportPropertyChanging("IALOMS7");
                _IALOMS7 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALOMS7");
                OnIALOMS7Changed();
            }
        }
        private global::System.String _IALOMS7;
        partial void OnIALOMS7Changing(global::System.String value);
        partial void OnIALOMS7Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALOMSE
        {
            get
            {
                return _IALOMSE;
            }
            set
            {
                OnIALOMSEChanging(value);
                ReportPropertyChanging("IALOMSE");
                _IALOMSE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALOMSE");
                OnIALOMSEChanged();
            }
        }
        private global::System.String _IALOMSE;
        partial void OnIALOMSEChanging(global::System.String value);
        partial void OnIALOMSEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALPDC1
        {
            get
            {
                return _IALPDC1;
            }
            set
            {
                OnIALPDC1Changing(value);
                ReportPropertyChanging("IALPDC1");
                _IALPDC1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALPDC1");
                OnIALPDC1Changed();
            }
        }
        private global::System.String _IALPDC1;
        partial void OnIALPDC1Changing(global::System.String value);
        partial void OnIALPDC1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALPDC2
        {
            get
            {
                return _IALPDC2;
            }
            set
            {
                OnIALPDC2Changing(value);
                ReportPropertyChanging("IALPDC2");
                _IALPDC2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALPDC2");
                OnIALPDC2Changed();
            }
        }
        private global::System.String _IALPDC2;
        partial void OnIALPDC2Changing(global::System.String value);
        partial void OnIALPDC2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALPDC3
        {
            get
            {
                return _IALPDC3;
            }
            set
            {
                OnIALPDC3Changing(value);
                ReportPropertyChanging("IALPDC3");
                _IALPDC3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALPDC3");
                OnIALPDC3Changed();
            }
        }
        private global::System.String _IALPDC3;
        partial void OnIALPDC3Changing(global::System.String value);
        partial void OnIALPDC3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALPDC4
        {
            get
            {
                return _IALPDC4;
            }
            set
            {
                OnIALPDC4Changing(value);
                ReportPropertyChanging("IALPDC4");
                _IALPDC4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALPDC4");
                OnIALPDC4Changed();
            }
        }
        private global::System.String _IALPDC4;
        partial void OnIALPDC4Changing(global::System.String value);
        partial void OnIALPDC4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALPDC5
        {
            get
            {
                return _IALPDC5;
            }
            set
            {
                OnIALPDC5Changing(value);
                ReportPropertyChanging("IALPDC5");
                _IALPDC5 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALPDC5");
                OnIALPDC5Changed();
            }
        }
        private global::System.String _IALPDC5;
        partial void OnIALPDC5Changing(global::System.String value);
        partial void OnIALPDC5Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALPDC6
        {
            get
            {
                return _IALPDC6;
            }
            set
            {
                OnIALPDC6Changing(value);
                ReportPropertyChanging("IALPDC6");
                _IALPDC6 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALPDC6");
                OnIALPDC6Changed();
            }
        }
        private global::System.String _IALPDC6;
        partial void OnIALPDC6Changing(global::System.String value);
        partial void OnIALPDC6Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALPDC7
        {
            get
            {
                return _IALPDC7;
            }
            set
            {
                OnIALPDC7Changing(value);
                ReportPropertyChanging("IALPDC7");
                _IALPDC7 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALPDC7");
                OnIALPDC7Changed();
            }
        }
        private global::System.String _IALPDC7;
        partial void OnIALPDC7Changing(global::System.String value);
        partial void OnIALPDC7Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALPRAL
        {
            get
            {
                return _IALPRAL;
            }
            set
            {
                OnIALPRALChanging(value);
                ReportPropertyChanging("IALPRAL");
                _IALPRAL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALPRAL");
                OnIALPRALChanged();
            }
        }
        private global::System.String _IALPRAL;
        partial void OnIALPRALChanging(global::System.String value);
        partial void OnIALPRALChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALPROC
        {
            get
            {
                return _IALPROC;
            }
            set
            {
                OnIALPROCChanging(value);
                ReportPropertyChanging("IALPROC");
                _IALPROC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALPROC");
                OnIALPROCChanged();
            }
        }
        private global::System.String _IALPROC;
        partial void OnIALPROCChanging(global::System.String value);
        partial void OnIALPROCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALP__1
        {
            get
            {
                return _IALP__1;
            }
            set
            {
                OnIALP__1Changing(value);
                ReportPropertyChanging("IALP__1");
                _IALP__1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALP__1");
                OnIALP__1Changed();
            }
        }
        private global::System.String _IALP__1;
        partial void OnIALP__1Changing(global::System.String value);
        partial void OnIALP__1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALP__2
        {
            get
            {
                return _IALP__2;
            }
            set
            {
                OnIALP__2Changing(value);
                ReportPropertyChanging("IALP__2");
                _IALP__2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALP__2");
                OnIALP__2Changed();
            }
        }
        private global::System.String _IALP__2;
        partial void OnIALP__2Changing(global::System.String value);
        partial void OnIALP__2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALP__3
        {
            get
            {
                return _IALP__3;
            }
            set
            {
                OnIALP__3Changing(value);
                ReportPropertyChanging("IALP__3");
                _IALP__3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALP__3");
                OnIALP__3Changed();
            }
        }
        private global::System.String _IALP__3;
        partial void OnIALP__3Changing(global::System.String value);
        partial void OnIALP__3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALP__4
        {
            get
            {
                return _IALP__4;
            }
            set
            {
                OnIALP__4Changing(value);
                ReportPropertyChanging("IALP__4");
                _IALP__4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALP__4");
                OnIALP__4Changed();
            }
        }
        private global::System.String _IALP__4;
        partial void OnIALP__4Changing(global::System.String value);
        partial void OnIALP__4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALP__5
        {
            get
            {
                return _IALP__5;
            }
            set
            {
                OnIALP__5Changing(value);
                ReportPropertyChanging("IALP__5");
                _IALP__5 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALP__5");
                OnIALP__5Changed();
            }
        }
        private global::System.String _IALP__5;
        partial void OnIALP__5Changing(global::System.String value);
        partial void OnIALP__5Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALP__6
        {
            get
            {
                return _IALP__6;
            }
            set
            {
                OnIALP__6Changing(value);
                ReportPropertyChanging("IALP__6");
                _IALP__6 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALP__6");
                OnIALP__6Changed();
            }
        }
        private global::System.String _IALP__6;
        partial void OnIALP__6Changing(global::System.String value);
        partial void OnIALP__6Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String IALP__7
        {
            get
            {
                return _IALP__7;
            }
            set
            {
                if (_IALP__7 != value)
                {
                    OnIALP__7Changing(value);
                    ReportPropertyChanging("IALP__7");
                    _IALP__7 = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("IALP__7");
                    OnIALP__7Changed();
                }
            }
        }
        private global::System.String _IALP__7;
        partial void OnIALP__7Changing(global::System.String value);
        partial void OnIALP__7Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALSALT
        {
            get
            {
                return _IALSALT;
            }
            set
            {
                OnIALSALTChanging(value);
                ReportPropertyChanging("IALSALT");
                _IALSALT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALSALT");
                OnIALSALTChanged();
            }
        }
        private global::System.String _IALSALT;
        partial void OnIALSALTChanging(global::System.String value);
        partial void OnIALSALTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALTALT
        {
            get
            {
                return _IALTALT;
            }
            set
            {
                OnIALTALTChanging(value);
                ReportPropertyChanging("IALTALT");
                _IALTALT = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALTALT");
                OnIALTALTChanged();
            }
        }
        private global::System.String _IALTALT;
        partial void OnIALTALTChanging(global::System.String value);
        partial void OnIALTALTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALTPQ1
        {
            get
            {
                return _IALTPQ1;
            }
            set
            {
                OnIALTPQ1Changing(value);
                ReportPropertyChanging("IALTPQ1");
                _IALTPQ1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALTPQ1");
                OnIALTPQ1Changed();
            }
        }
        private global::System.String _IALTPQ1;
        partial void OnIALTPQ1Changing(global::System.String value);
        partial void OnIALTPQ1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALTPQ2
        {
            get
            {
                return _IALTPQ2;
            }
            set
            {
                OnIALTPQ2Changing(value);
                ReportPropertyChanging("IALTPQ2");
                _IALTPQ2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALTPQ2");
                OnIALTPQ2Changed();
            }
        }
        private global::System.String _IALTPQ2;
        partial void OnIALTPQ2Changing(global::System.String value);
        partial void OnIALTPQ2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALTPQ3
        {
            get
            {
                return _IALTPQ3;
            }
            set
            {
                OnIALTPQ3Changing(value);
                ReportPropertyChanging("IALTPQ3");
                _IALTPQ3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALTPQ3");
                OnIALTPQ3Changed();
            }
        }
        private global::System.String _IALTPQ3;
        partial void OnIALTPQ3Changing(global::System.String value);
        partial void OnIALTPQ3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALINFO
        {
            get
            {
                return _IALINFO;
            }
            set
            {
                OnIALINFOChanging(value);
                ReportPropertyChanging("IALINFO");
                _IALINFO = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALINFO");
                OnIALINFOChanged();
            }
        }
        private global::System.String _IALINFO;
        partial void OnIALINFOChanging(global::System.String value);
        partial void OnIALINFOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALDIA1
        {
            get
            {
                return _IALDIA1;
            }
            set
            {
                OnIALDIA1Changing(value);
                ReportPropertyChanging("IALDIA1");
                _IALDIA1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALDIA1");
                OnIALDIA1Changed();
            }
        }
        private global::System.String _IALDIA1;
        partial void OnIALDIA1Changing(global::System.String value);
        partial void OnIALDIA1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALDIA2
        {
            get
            {
                return _IALDIA2;
            }
            set
            {
                OnIALDIA2Changing(value);
                ReportPropertyChanging("IALDIA2");
                _IALDIA2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALDIA2");
                OnIALDIA2Changed();
            }
        }
        private global::System.String _IALDIA2;
        partial void OnIALDIA2Changing(global::System.String value);
        partial void OnIALDIA2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALDIA3
        {
            get
            {
                return _IALDIA3;
            }
            set
            {
                OnIALDIA3Changing(value);
                ReportPropertyChanging("IALDIA3");
                _IALDIA3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALDIA3");
                OnIALDIA3Changed();
            }
        }
        private global::System.String _IALDIA3;
        partial void OnIALDIA3Changing(global::System.String value);
        partial void OnIALDIA3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALDIA4
        {
            get
            {
                return _IALDIA4;
            }
            set
            {
                OnIALDIA4Changing(value);
                ReportPropertyChanging("IALDIA4");
                _IALDIA4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALDIA4");
                OnIALDIA4Changed();
            }
        }
        private global::System.String _IALDIA4;
        partial void OnIALDIA4Changing(global::System.String value);
        partial void OnIALDIA4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALDIA5
        {
            get
            {
                return _IALDIA5;
            }
            set
            {
                OnIALDIA5Changing(value);
                ReportPropertyChanging("IALDIA5");
                _IALDIA5 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALDIA5");
                OnIALDIA5Changed();
            }
        }
        private global::System.String _IALDIA5;
        partial void OnIALDIA5Changing(global::System.String value);
        partial void OnIALDIA5Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALDIA6
        {
            get
            {
                return _IALDIA6;
            }
            set
            {
                OnIALDIA6Changing(value);
                ReportPropertyChanging("IALDIA6");
                _IALDIA6 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALDIA6");
                OnIALDIA6Changed();
            }
        }
        private global::System.String _IALDIA6;
        partial void OnIALDIA6Changing(global::System.String value);
        partial void OnIALDIA6Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALDIA7
        {
            get
            {
                return _IALDIA7;
            }
            set
            {
                OnIALDIA7Changing(value);
                ReportPropertyChanging("IALDIA7");
                _IALDIA7 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALDIA7");
                OnIALDIA7Changed();
            }
        }
        private global::System.String _IALDIA7;
        partial void OnIALDIA7Changing(global::System.String value);
        partial void OnIALDIA7Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALDIAE
        {
            get
            {
                return _IALDIAE;
            }
            set
            {
                OnIALDIAEChanging(value);
                ReportPropertyChanging("IALDIAE");
                _IALDIAE = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALDIAE");
                OnIALDIAEChanged();
            }
        }
        private global::System.String _IALDIAE;
        partial void OnIALDIAEChanging(global::System.String value);
        partial void OnIALDIAEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALPDT1
        {
            get
            {
                return _IALPDT1;
            }
            set
            {
                OnIALPDT1Changing(value);
                ReportPropertyChanging("IALPDT1");
                _IALPDT1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALPDT1");
                OnIALPDT1Changed();
            }
        }
        private global::System.String _IALPDT1;
        partial void OnIALPDT1Changing(global::System.String value);
        partial void OnIALPDT1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALPDT2
        {
            get
            {
                return _IALPDT2;
            }
            set
            {
                OnIALPDT2Changing(value);
                ReportPropertyChanging("IALPDT2");
                _IALPDT2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALPDT2");
                OnIALPDT2Changed();
            }
        }
        private global::System.String _IALPDT2;
        partial void OnIALPDT2Changing(global::System.String value);
        partial void OnIALPDT2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALPDT3
        {
            get
            {
                return _IALPDT3;
            }
            set
            {
                OnIALPDT3Changing(value);
                ReportPropertyChanging("IALPDT3");
                _IALPDT3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALPDT3");
                OnIALPDT3Changed();
            }
        }
        private global::System.String _IALPDT3;
        partial void OnIALPDT3Changing(global::System.String value);
        partial void OnIALPDT3Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALPDT4
        {
            get
            {
                return _IALPDT4;
            }
            set
            {
                OnIALPDT4Changing(value);
                ReportPropertyChanging("IALPDT4");
                _IALPDT4 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALPDT4");
                OnIALPDT4Changed();
            }
        }
        private global::System.String _IALPDT4;
        partial void OnIALPDT4Changing(global::System.String value);
        partial void OnIALPDT4Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALPDT5
        {
            get
            {
                return _IALPDT5;
            }
            set
            {
                OnIALPDT5Changing(value);
                ReportPropertyChanging("IALPDT5");
                _IALPDT5 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALPDT5");
                OnIALPDT5Changed();
            }
        }
        private global::System.String _IALPDT5;
        partial void OnIALPDT5Changing(global::System.String value);
        partial void OnIALPDT5Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALPDT6
        {
            get
            {
                return _IALPDT6;
            }
            set
            {
                OnIALPDT6Changing(value);
                ReportPropertyChanging("IALPDT6");
                _IALPDT6 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALPDT6");
                OnIALPDT6Changed();
            }
        }
        private global::System.String _IALPDT6;
        partial void OnIALPDT6Changing(global::System.String value);
        partial void OnIALPDT6Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALPDT7
        {
            get
            {
                return _IALPDT7;
            }
            set
            {
                OnIALPDT7Changing(value);
                ReportPropertyChanging("IALPDT7");
                _IALPDT7 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALPDT7");
                OnIALPDT7Changed();
            }
        }
        private global::System.String _IALPDT7;
        partial void OnIALPDT7Changing(global::System.String value);
        partial void OnIALPDT7Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALPRQ1
        {
            get
            {
                return _IALPRQ1;
            }
            set
            {
                OnIALPRQ1Changing(value);
                ReportPropertyChanging("IALPRQ1");
                _IALPRQ1 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALPRQ1");
                OnIALPRQ1Changed();
            }
        }
        private global::System.String _IALPRQ1;
        partial void OnIALPRQ1Changing(global::System.String value);
        partial void OnIALPRQ1Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALPRQ2
        {
            get
            {
                return _IALPRQ2;
            }
            set
            {
                OnIALPRQ2Changing(value);
                ReportPropertyChanging("IALPRQ2");
                _IALPRQ2 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALPRQ2");
                OnIALPRQ2Changed();
            }
        }
        private global::System.String _IALPRQ2;
        partial void OnIALPRQ2Changing(global::System.String value);
        partial void OnIALPRQ2Changed();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String IALPRQ3
        {
            get
            {
                return _IALPRQ3;
            }
            set
            {
                OnIALPRQ3Changing(value);
                ReportPropertyChanging("IALPRQ3");
                _IALPRQ3 = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("IALPRQ3");
                OnIALPRQ3Changed();
            }
        }
        private global::System.String _IALPRQ3;
        partial void OnIALPRQ3Changing(global::System.String value);
        partial void OnIALPRQ3Changed();

        #endregion
    
    }

    #endregion
    
}
